# This rule is not used by the project flowbox itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over devflow.flowbox.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flowbox
    app.kubernetes.io/managed-by: kustomize
  name: flowbox-admin-role
rules:
- apiGroups:
  - devflow.flowbox.io
  resources:
  - flowboxes
  verbs:
  - '*'
- apiGroups:
  - devflow.flowbox.io
  resources:
  - flowboxes/status
  verbs:
  - get
