# This rule is not used by the project flowbox itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to devflow.flowbox.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flowbox
    app.kubernetes.io/managed-by: kustomize
  name: flowbox-viewer-role
rules:
- apiGroups:
  - devflow.flowbox.io
  resources:
  - flowboxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devflow.flowbox.io
  resources:
  - flowboxes/status
  verbs:
  - get
