# This rule is not used by the project flowbox itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the devflow.flowbox.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flowbox
    app.kubernetes.io/managed-by: kustomize
  name: flowbox-editor-role
rules:
- apiGroups:
  - devflow.flowbox.io
  resources:
  - flowboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devflow.flowbox.io
  resources:
  - flowboxes/status
  verbs:
  - get
