apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flowbox-manager-role
rules:
  - apiGroups:
      - devflow.flowbox.io
    resources:
      - flowboxes
      - flowboxes/status
      - flowboxes/finalizers
    verbs:
      - '*'

  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'

  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - '*'

  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - '*'