apiVersion: devflow.flowbox.io/v1
kind: FlowBox
metadata:
    labels:
        app.kubernetes.io/name: flowbox
        app.kubernetes.io/managed-by: kustomize
    name: demo
    namespace: flowbox-system
spec:
    # TODO(user): Add fields here
    port: 80
    image: harbor.chengduoduo.com/base/nginx:demo
    replicas: 1
    probe: false
    resource:
        enabled: false
    hpa:
        enabled: true
        min: 1
        max: 3
        cpuQuantity: 80
        memoryQuantity: 60
    ingress:
        enabled: true
        domain: nginx.domain.com

